### ISSUE TITLE
あとどの程度機能を作り込めばMVPリリース出来るか。

### ISSUE THREAD

**Issue by TAMETOMO8** [TAMETOMO8/Haburashi_Life#45]
表題にある通り、自分のアプリはあとどの程度機能を実装していけばMVPリリースと呼べる段階になるのか把握したいと考えご質問させていただきます。
現在、READMEで定義したMVPリリース時に実装したい機能の内、次の機能を実装済み、もしくは実装間近だと考えています。

* LINEを使用したログイン機能
* 楽天APIを使用した歯ブラシの検索機能
* 検索結果に表示された歯ブラシの登録機能(現在行えるのはただ登録するだけ)
* 使用されている歯ブラシの一覧表示(機能は完成したのでフロントエンドを整える必要あり)
* Messaging APIを使用したユーザーへの通知機能(現在機能しているのは友達登録を行ったユーザーの歯ブラシ登録時に行う通知のみ)

次に、READMEで定義した中で未実装の機能が次のものです。
* 歯ブラシの詳細画面
* ユーザー登録機能
この内、ユーザー登録機能は開発を進める中でLINEログイン時にデフォルトで設定されるユーザー名を定義し、それを後から編集できるようにする方が最初にサービスに触れるまでの時間を短縮できると考えたため、ユーザー編集機能として実装を行いたいと考えています。

そして、開発を進める中で、MVPまでにこういう機能を実装したいとより具体的になった機能、実装した方が良いのではないかと考えるようになった機能、MVPまでに整理しておいた方がいいと考えているものが次のようになります。
* トップページの充実
* 歯ブラシ登録時に歯ブラシの交換時期、ブラシの材質を登録する機能
* 歯ブラシの編集画面、編集機能の作成
* 歯ブラシの削除
* 任意のタイミングでユーザーが歯ブラシの使用を終了出来る機能
* Messaging API、rakeタスク、schedule.rbを併用して、交換時期が来た歯ブラシを使用しているユーザーにのみ通知を送る機能
* LION歯ブラシリサイクルプログラムを案内するページの実装
* 歯ブラシの状態(使用中、交換時期が来た、掃除用具として使用中、リサイクル済み等)を判別できる機能の実装
* 各ページにアクセスしやすくなるようにヘッダーの作成
* フラッシュメッセージの表示箇所が想定と異なるのでその修正
* ログインしていないユーザーが一部ページにアクセスを試みた場合に、ログインページへ遷移させる機能
* ユーザーがログイン済みの場合に、ログインページに移動しなくなる機能
* スマートフォンでアプリを使用する際に画面表示の比率が適切になるようにする機能

これに加え、現在実装している全てのページのフロントエンドも、必要最低限の物しか実装されていない状態です(甘く見てRUNTEQカリキュラムの基礎編で作成した物とほぼ同程度のレベルです)
コミュニティ卒業日が11/7と期日が迫っているのもあり、MVPで全てを実装するのは困難だと考えています。しかし、MVPリリースには上記の全てを実装しなければ基準を満たさないのではないかとも考えています。
どの機能がMVPに必要で、どの機能なら本リリースまでの実装に回しても問題ないか、フロントエンドはどの程度作り込めば最低限と呼べるか、上記以外でMVPに必要な要素を見落としていないか、ご意見を伺いたいと思います。

本日(10/24)、仕事の関係でレビューの確認及び返信が遅くなってしまいます。ご迷惑おかけしますが、よろしくお願いします。

**Comment by Tsuchiya2** [comment]
READMEレビュー時のやり取り（ https://github.com/TAMETOMO8/Haburashi_Life/pull/2 ）を満たす状態まで達したらMVPリリースで良いかと思います。

**Comment by TAMETOMO8** [comment]
READMEレビュー時に定義した、MVPリリース時に実装したい機能が次のものです。

* ログイン機能
* ユーザー作成機能
* 使用されている歯ブラシ一覧表示
* LINEを使用したユーザーへの通知機能

上記のうち、未実装の機能はユーザー作成機能と考えています。
また、MVP実装時に必要なのではないかと考えた機能のうち、未実装の機能及びREADMEレビュー時の機能に付随するものが次のものだと考えています。

* Messaging API、rakeタスク、schedule.rbを併用して、交換時期が来た歯ブラシを使用しているユーザーにのみ通知を送る機能
* 歯ブラシの状態(使用中、交換時期が来た、掃除用具として使用中、リサイクル済み等)を判別できる機能の実装

上記二つとユーザー登録機能の完成をもって、MVPリリースを行いたいと思います。
フロントエンドに関しては、READMEレビュー時に完成度の指定を行っていないのと、今回頂いたレビューにて言及されていないことを踏まえ、現状の完成度でMVPを行いたいと思います。
この方針で開発を進めたいと考えますが、ご意見ございましたら伺いたいと思います。

**Comment by Tsuchiya2** [comment]
特に意見はありません。MVPレビューは先程共有したものをもとに行いますし、サービスの開発に明確な基準による線引はないかと思うので、引き続き開発を進めていただければと思います。

**Comment by TAMETOMO8** [comment]
レビューいただき、ありがとうございます。
引き続き開発を進めていきます！
