### ISSUE TITLE
MVPレビュー前に

### ISSUE THREAD

**Issue by Tsuchiya2** [TAMETOMO8/Haburashi_Life#56]
挙動確認を行いまして、MVP機能に書かれている実装はできていること・動いていることを確認できました。
LGTMです！

明日以降、講師陣でMVPレビューを行い、レビュー内容をお返ししますので、その際はご対応をよろしくお願いいたします。

**Comment by TAMETOMO8** [comment]
お手数をおかけし申し訳ありません、ご確認ありがとうございます！
