### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [TAMETOMO8/Haburashi_Life#59]
@TAMETOMO8 
MVPレビューでございます。

## 技術
- 通知来ないかもなので確認してみてください（未実装の場合は実装しましょう）
- 就活に向けては機能を増やしていく必要があるので、READMEに記載されている内容は実装してください。
- 他ユーザーのデータを改変できるので修正してください。
- 検索部分はオートコンプリート機能を入れ込んで技術を増やしておきましょう。
- 全体的にcontrollerの処理はmodelに寄せられる部分があるのでmodelに処理を切り出しましょう。（定数など）

## UI/UX
- 検索周りの処理が重たく感じてしまうので、パフォーマンスチューイングの対応してみてください。（検索に時間がかかるので「データ取得中...」とかでサークル出してあげても良いかも）
- 歯ブラシ一覧に他者登録の歯ブラシが出ており、それをどう活用して良いかが直感的には分かりにくいので他ユーザーと自分を区別して表示などするようにしてみてください。
- ユーザー登録して名前が「ゲスト」表記になっている登録時の情報を利用したり、登録時に名前も登録してもらうなどしてみてください。
- 歯ブラシの検索する際にメーカーとか覚えてないかもなので、画像分析など利用して歯ブラシ登録の動線をより楽になるようにしてみてください。
- ログイン・ログアウト時にUI変える。（ログイン時にログインの動線が出ているので）
- 使用終了日は時間なしで、日付だけにしましょう。
- 登録した後の導線がわからないので、使い方ページをTOP以外にも動線を入れてみましょう。
- 新しい歯ブラシを検索時に有名メーカーのサジェストがあると探しやすいかもなので、参考にしてみてください。
- 詳細情報で楽天に飛ばされるので、このアプリ内の詳細情報を出してその中に楽天への導線を入れておきましょう。

上記内容を確認いただき、issueにタスクを落とし込めたら、こちらのissueはcloseして構いません。

また上記内容を実装するにあたり、スケジュールを立ててみてください。
スケジュール決まりましたら共有ください。

また質問などありましたらスレッドに記載いただいて連絡いただければでございます！

**Comment by TAMETOMO8** [comment]
MVPレビューありがとうございます、大変参考になりました！

今回頂いたレビュー内容の機能実装までのスケジュールとしましては、11月24日までに実装完了を目標にしたいと考えています。

また、README記載の本リリースまでに行いたい機能実装の目標につきましては、途中から就活準備と並行を始め今月末までに実装完了を目標に、遅れる場合でも12/10までには実装完了し、本リリースを行うことを目指して開発を進めたいと考えています。

加えて、通知が来ない部分についての質問です。
現在は歯ブラシの登録成功時の通知と、設定された使用終了日を過ぎた歯ブラシが存在する場合、その歯ブラシを使用されているユーザーへの通知を設定しているのですが、アプリを触っている際に通知が来なかったのはどの部分だったでしょうか？
コメントを頂ければ幸いです！

**Comment by kerochelo** [comment]
@TAMETOMO8 
通知自体がそもそも来なかったのでどうしたのかなといった感じでした。
再度確認しますね！

**Comment by TAMETOMO8** [comment]
失礼しました、ログイン後かつ友達登録を行なっていただいたLINEのアカウントにのみ通知が送られるようになっています！

通知が来なかったということは友達登録がされていない可能性が高いので、友達登録までの導線をどうするかについても検討していきます。

**Comment by kerochelo** [comment]
なるほどです！そこも含めて修正していきましょう！

**Comment by kerochelo** [comment]
UI/UXに関するもの

## 優先度低め
### 全体系
- TOPのみんなの歯ブラシへのリンクはボタンにしてあげる
- 一覧ページの「歯ブラシ一覧」はなくてOK
- 一覧ページの商品名は文字数制限して、ポインターがホバーすると商品名全部が出てくる
- ブラシの材質、ブラシの硬さはタグっぽいUIにする
- ヘッダーはプルダウン2つ
  - 歯ブラシ系（みんなの歯ブラシを探す、新しい歯ブラシを探す）
  - ユーザー系（マイページ、ログアウト）

### 一覧ページ
一覧ページは情報量を少なくする
- 歯ブラシ画像
- 商品名
- 詳細ボタン

一覧画面は4*4でページネーションを入れる

### 詳細ページ
詳細ページは使っているユーザー情報の詳細ではなく、そのユーザーの使っている歯ブラシ、グッズ一覧への導線にする
商品名のリンクは外して、楽天へのボタンを作る
使用状況はなくす
「歯ブラシの詳細」の文言もなくす


### ユーザーページ（マイページ）
「ユーザーページ」の文言もなくす
ユーザー名表示、ユーザー編集リンクもなくす（代わりにユーザー設定のボタンを配置する）
「これまで使用した歯ブラシ」もなくす、代わりに「マイ歯ブラシ&グッズ」とかにする
編集ボタンを作る&グッズ登録ボタンもつくる
デザインは縦に並べる（画像、商品名、使用状況、使用終了日）
使用終了日を過ぎているものは背景を赤にする、1週間以内に迎えるものは黄色にする....

## 優先度低め
一覧ページでみんなが登録している歯ブラシorグッズの検索フォームを作る
TOPページの画像読み込みが初回は遅いので、画像の読み込みを早くする調査する

**Comment by kerochelo** [comment]
上記のUI/UXと技術の部分をissueにする
あとは一旦のスケジュールを作る
できたら、ここのコメントに共有お願いします！

**Comment by TAMETOMO8** [comment]
以下にissueをまとめました。

## UI/UXに関するissue

#60    12/12完了
#64    12/10
#65    12/17
#66    12/17
#67    12/15
#68    12/10
#69    12/10
#70    12/13
#71     12/10
#73    12/10


## READMEに記載した本リリースまでに実装したい機能のissue

#75    12/15完了
#76    12/15
#77    12/15


12/17までに上記のタスクの完了を目標にして進めてみようと考えています！

**Comment by TAMETOMO8** [comment]
@kerochelo 
目標期日に間に合わないものがいくつかあるので、以下のissueについてスケジュールを見直します。

- [ ] #60   12/22完了
- [ ] #65   12/22
- [ ] #66   12/22   
- [ ] #75    12/20
- [ ] #76    12/20
- [ ] #77    12/22


以上です、よろしくお願いします！

**Comment by kerochelo** [comment]
@TAMETOMO8 
確認しました、引き続き頑張っていきましょ！
